### ISSUE TITLE
TypeScript types?

### ISSUE THREAD

**Issue by ktwbc** [jeremydaly/lambda-warmer#20]
Can you include an index.d.ts file to export TypeScript types?

**Comment by hom-bahrani** [comment]
Try this for the time being..

```js
/* eslint-disable @typescript-eslint/no-var-requires */
const warmer = require('lambda-warmer');
/* eslint-enable @typescript-eslint/no-var-requires */
```

**Comment by alopix** [comment]
There actually is a PR already for this: https://github.com/jeremydaly/lambda-warmer/pull/17
Would be amazing if it could be merged, please!
