### ISSUE TITLE
Find optimal concurrency level

### ISSUE THREAD

**Issue by masotrix** [jeremydaly/lambda-warmer#34]
Hi, we have a huge application that without qarming gets to 16 concurrency We have set the concurrency level of warmup to 20, but now rhe concurrency level gets to 24

Our application does some very intensive processin which can take up to 27 seconds, which makes us think that may be beating lambda-warmer because of lambda-warmer keeping busy the concurrent lambdas when this happens or something similar

Does this make sense? What procedure would you recommend to find the optimal lambda-warmer concurrency level?

**Comment by naorpeled** [comment]
Lambda warmer works great for small admin apps that power APIs, but for something like this, it's probably not going to be optimal.

Also, if your handler runs for 27 seconds, I'm not sure cold starts are the issue.
