### ISSUE TITLE
Issues using from a lambda in VPC

### ISSUE THREAD

**Issue by santigimeno** [jeremydaly/lambda-warmer#4]
Hi,

I started playing with the module and it worked great for lambda not associated to a VPC, but I couldn't make it work with lambda inside a VPC: the invocation timed out. I've read somewhere that it could be because I need to configure internet access for this case. Is this correct?

Thanks in advance, and thanks for the module.

**Comment by jeremydaly** [comment]
Sorry for the delay and thanks for the report. I am researching the issue.

**Comment by carlitux** [comment]
After enable access to lambda functions inside a VPC, I saw that errors go out.

**Comment by naorpeled** [comment]
Hey @santigimeno,
thanks for opening this issue and sorry for the delayed response.

[This](https://github.com/jeremydaly/lambda-warmer/issues/5#issuecomment-490705931) comment will probably resolve the issue for you.

I'll be closing this issue for now, feel free to ping me if you need anything.
