### ISSUE TITLE
Alias support: lambda-warmer ignores alias when invoked with a tag and concurrency > 1

### ISSUE THREAD

**Issue by Jimmy89** [jeremydaly/lambda-warmer#56]
Setup:
- Eventbridge calling lambda alias
- Lambda calling itself another two time because of concurreny: 3 setting.

When a lambda with alias is invoked by event bridge with `concurrency: 3`, it will invoke the alias once. The alias will try to invoke itself another two times. However, the alias that is provided is ignored by the warmer function and therefore the `latest` tag is called.

I checked whether the target provided to the warmer function contains the alias, which it does. It seems the code does not use this part.

Code snippet:
```
console.log("I'm invoked",  context.invokedFunctionArn); // <-- contains the first call the function + ":ALIAS" tag.
    if (await warmer(event, { correlationId: context.awsRequestId, target: context.invokedFunctionArn })) {
        return 'warmed'
    }
```

Update:

after going through the code I notice two things:

1. The code does not count on aliases being used (because it expects the target to match the function name, adding an alias or version number, being the same as the one executed, will be seen as a 'different' function).
2. For an alias the `Qualifier` key must be sent with the InvokeCommand.

**Comment by naorpeled** [comment]
Hey @Jimmy89 

thanks for opening this issue, you're awesome!

I'm on vacation until mid next week, will keep you updated with the progress

**Comment by naorpeled** [comment]
Hey,
just updating that I've been super busy in the last two weeks, will try to get to it towards this weekend.
Thanks for your patience ❤️

**Comment by Jimmy89** [comment]
@naorpeled Will you have any time soon to address this issue?
