### ISSUE TITLE
 Could not resolve "@aws-sdk/client-lambda"

### ISSUE THREAD

**Issue by DecioLuczynski** [jeremydaly/lambda-warmer#57]
looks like "@aws-sdk/client-lambda" is a devDependency and needs to be a dependency.

Bundling asset platform-portal-stack/signOutWs/Code/Stage...
Error: R] Could not resolve "@aws-sdk/client-lambda"

    node_modules/lambda-warmer/lib/lambda-service.js:9:48:
      9 │ ...{ LambdaClient, InvokeCommand } = require('@aws-sdk/client-lambda')
        ╵                                              ~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@aws-sdk/client-lambda" as external to exclude it from the bundle, which will remove this error. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.

1 error
node:child_process:924
    throw err;
    ^

**Comment by naorpeled** [comment]
Hey @DecioLuczynski,
which node version are you running?

**Comment by DecioLuczynski** [comment]
16.20.1

**Comment by naorpeled** [comment]
> 16.20.1
> 

Node 16 comes out of the box with AWS SDK v2.
You'd need to install v1 of  lambda warmer or upgrade your lambda to use Node 18.

**Comment by naorpeled** [comment]
Hey @DecioLuczynski,
I'll be closing this issue for now.

If you have any questions feel free to ping me.
