### ISSUE TITLE
lambda-warmer ignores value of AWS_LAMBDA_FUNCTION_VERSION

### ISSUE THREAD

**Issue by CH43-dev** [jeremydaly/lambda-warmer#58]
Hi!
After upgrade to version 2.0.0 (because of AWS SDK v3 support) it was necessary to change our IAM policy because lambda-warmer is ignoring the value of AWS_LAMBDA_FUNCTION_VERSION. The value will still be used to create the log-record but it will be ignored afterwards:

...
const funcName = process.env.AWS_LAMBDA_FUNCTION_NAME
const funcVersion = process.env.AWS_LAMBDA_FUNCTION_VERSION
...
 // Create log record
    let log = {
      action: 'warmer',
      function: funcName + ':' + funcVersion,
...
I think the functionality is changed since version 1.3.0 – support multiple targets. Is this the expected behavior?

**Comment by naorpeled** [comment]
Hey @CH43-dev,
I'll be honest and say I'm not sure.

Will be able to take a look on Friday, I hope that's okay 🙏

**Comment by CH43-dev** [comment]
Hi @naorpeled,

In version 1.2.3,  lambda-warmer has used funcName + ':' + funcVersion as FunctionName. Since version 1.3.0 it is using target ->  let target = event[config.target] || funcName

**Comment by naorpeled** [comment]
I've merged a PR that resolves this issue,
will mark this issue as resolved.

Please let me know if something is still off.
