### ISSUE TITLE
Support for aliases is missing

### ISSUE THREAD

**Issue by Jimmy89** [jeremydaly/lambda-warmer#66]
The current version (2.0.1) does not support alias names for lambda invocations. I support the "$LATEST" tag and version numbers, but not any other alias e.g. `stable`. Therefore, if a lambda is called with the `stable` tag the code thinks a different lambda version must be called as `isDifferentTarget` is set to true (because the lambda version number is used for comparison instead of the tag). Therefore, it tries to call the lambda again instead of triggering a delay.

**Comment by naorpeled** [comment]
Hey,
great point, working on a fix for it 🙏 

Will ping you here when it's resolved.
