### ISSUE TITLE
new Buffer is deprecated in nodejs 10.x

### ISSUE THREAD

**Issue by aaliakseyenka** [jeremydaly/lambda-warmer#8]
when running on runtime 10.x deprecation error is logged:
``
ERROR	(node:7) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
``
can you please update `new Buffer` => `Buffer.from`

**Comment by aaliakseyenka** [comment]
I've addd PR https://github.com/jeremydaly/lambda-warmer/pull/9

**Comment by jeremydaly** [comment]
Thanks. This has been merged in the latest release.
